instances:
  - config:
      host: "localhost"
      port: 3306
      username: "root"
      password: ""
      pool:
        max_idle_conns: 10
        max_open_conns: 100
    databases:
      - name: "test"
        mode: "readonly"
      - name: "test"
        mode: "readwrite"
  - config:
      host: "host2"
      # ... 其他实例配置