instances:
  - config:
      host: "localhost"
      port: 3306
      username: "root"
      password: "123456"
      mode: "readonly"
      pool:
        max_idle_conns: 10
        max_open_conns: 100
      log:
        level: "info"  # 可选值: silent, error, warn, info
    databases:
      - name: "test"
      - name: "test"
  - config:
      host: "host2"
      # ... 其他实例配置