# MySQL实例配置
[[instances]]
# 第一个实例配置
[instances.config]
host = "localhost"
port = 3306
username = "root"
password = "123456"
mode = "readonly"  # 访问模式: readonly 或 readwrite

# 连接池配置
[instances.config.pool]
max_idle_conns = 10  # 最大空闲连接数
max_open_conns = 100 # 最大打开连接数

# 日志配置
[instances.config.log]
level = "info"  # 可选值: silent, error, warn, info

# 数据库配置
[[instances.databases]]
name = "test"

[[instances.databases]]
name = "test"

# 第二个实例配置（示例）
[[instances]]
[instances.config]
host = "host2"
port = 3306
username = "user2"
password = "pass2"
mode = "readwrite"  # 访问模式: readonly 或 readwrite

[instances.config.pool]
max_idle_conns = 5
max_open_conns = 50

# 日志配置
[instances.config.log]
level = "info"  # 可选值: silent, error, warn, info

[[instances.databases]]
name = "db2"


